# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseos:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/hyperledger/fabric
RUN mkdir -p /etc/hyperledger
RUN mkdir -p /var/hyperledger/production $FABRIC_CFG_PATH
RUN mkdir -p /var/hyperledger/production/orderer
COPY payload/orderer /usr/local/bin
ADD payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH/

RUN groupadd --gid 1024 llsuser     && useradd --home-dir /home/llsuser --create-home --uid 1024         --gid 1024 --shell /bin/sh --skel /dev/null llsuser
RUN chown -R llsuser:llsuser /etc/hyperledger
RUN chown -R llsuser:llsuser /var/hyperledger
RUN chown -R llsuser:llsuser /opt
USER llsuser

EXPOSE 7050
CMD ["orderer"]
